# Generated by Django 3.2.8 on 2021-11-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(max_length=100)),
                ('contact_last_name', models.CharField(max_length=100)),
                ('contact_mobile_number', models.CharField(max_length=12)),
                ('contact_text', models.TextField()),
                ('contact_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
