# Generated by Django 3.2.8 on 2021-11-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_first_name', models.CharField(max_length=100)),
                ('donor_last_name', models.CharField(max_length=100)),
                ('donor_phone_number', models.CharField(max_length=12)),
                ('donor_organization_name', models.CharField(max_length=100)),
                ('donor_email', models.CharField(max_length=100)),
                ('donor_address', models.CharField(max_length=300)),
                ('donor_country', models.CharField(max_length=100)),
                ('donor_state', models.CharField(max_length=100)),
                ('donor_city', models.CharField(max_length=100)),
                ('donor_zip', models.CharField(max_length=10)),
                ('donor_amount', models.CharField(max_length=100)),
                ('donor_txnid', models.CharField(max_length=20)),
                ('donoration_time', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(max_length=50)),
            ],
        ),
    ]
