# Generated by Django 3.2.8 on 2021-11-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_donors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donors',
            new_name='Donor',
        ),
    ]
