# Generated by Django 3.2.8 on 2021-11-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_donor_donoration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
                ('eventStartDate', models.CharField(max_length=200)),
                ('eventEndDate', models.CharField(max_length=200)),
                ('Descreption', models.TextField()),
            ],
        ),
    ]
