# Generated by Django 3.2.8 on 2021-11-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_txnid', models.CharField(max_length=50)),
                ('expenditure_by_name', models.CharField(max_length=100)),
                ('expenditure_work', models.CharField(max_length=200)),
                ('expenditure_date', models.DateTimeField(auto_now_add=True)),
                ('expenditure_amount', models.CharField(max_length=50)),
            ],
        ),
    ]
